// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmRWfHa7A9Gq5zB5iYZBVn2a9ifOF888Y',
    appId: '1:1095358418186:web:3e09d10673198b99df3ef3',
    messagingSenderId: '1095358418186',
    projectId: 'smartsafe-c33bc',
    authDomain: 'smartsafe-c33bc.firebaseapp.com',
    storageBucket: 'smartsafe-c33bc.firebasestorage.app',
    measurementId: 'G-4VF391PRTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDYIyCut7n3yI4YKIwpw9bdjhnAq_HHjE',
    appId: '1:1095358418186:android:df7857a37c42d905df3ef3',
    messagingSenderId: '1095358418186',
    projectId: 'smartsafe-c33bc',
    storageBucket: 'smartsafe-c33bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUacou0Inf_YDDe86Ttb2ca3i33cj7QLQ',
    appId: '1:1095358418186:ios:0e1c0dea403fcb73df3ef3',
    messagingSenderId: '1095358418186',
    projectId: 'smartsafe-c33bc',
    storageBucket: 'smartsafe-c33bc.firebasestorage.app',
    iosBundleId: 'com.example.smartSafe',
  );
}
